#source 'https://github.com/EricCheungSCUT/qcloud-sdk-ios.git'
use_frameworks!

target 'QCloudCOSXMLDemo' do
pod 'QCloudCoreTestTest',:tag=>'5.0.1',:git=>'https://github.com/EricCheungSCUT/qcloud-sdk-ios.git'
pod 'QCloudCOSXML',:git=>'https://github.com/EricCheungSCUT/qcloud-sdk-ios.git'
end
