#source 'https://github.com/EricCheungSCUT/qcloud-sdk-ios.git'
use_frameworks!

target 'QCloudCOSXMLDemo' do
pod 'QCloudCore',:tag=>'5.0.0',:git=>'https://github.com/EricCheungSCUT/qcloud-sdk-ios.git'
pod 'QCloudCOSXML',:git=>'https://github.com/EricCheungSCUT/qcloud-sdk-ios.git'
end
